# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'pagination' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for pagination
     pod 'Alamofire', '~> 4.2.0'               #Required
     pod 'MBProgressHUD', '~> 1.0.0'           #Required
     pod 'Kingfisher', '~> 4.2.0'
     pod 'ReachabilitySwift', '~> 3.0'
     
  target 'paginationTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'paginationUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
